### ISSUE TITLE
Arquivo QUEUES faltando

### ISSUE THREAD

**Issue by mcscunha** [zerossB/Labirinto-IA#2]
Pessoal,

Por favor, postem o seguinte arquivo:

 File "...\Labirinto-IA-master\base\buscas.py", line 12, in <module>
    from base.queues import ReversePriorityQueue
ModuleNotFoundError: No module named 'base.queues'

Obrigado

**Comment by zerossB** [comment]
Fala murilo, tudo bem? 

Obrigado por avisar, ja vou colocar esse arquivo la. Por algum motivo ele não subiu junto com o projeto, porém ja foi adicionado!

**Comment by mcscunha** [comment]
ZerossB,

Muito obrigado pela RAPIDEZ e pela contribuicao VALIOZISSIMA.
Adorei o projeto, vou apresenta-lo a meus amigos.
Ajudou bastante nas aulas de IA.

Obrigado.
